### ISSUE TITLE
Hi! Thanks for your excellent work! I would like to know what directory structure the dataset should be stored in.

### ISSUE THREAD

**Issue by blz822** [WkEEn/PAMA#1]
Hi! Thanks for your excellent work! I would like to know what directory structure the dataset should be stored in.

**Comment by WkEEn** [comment]
> Hi! Thanks for your excellent work! I would like to know what directory structure the dataset should be stored in.

Thanks for your attention. We have updated the code for extracting patch features and the directory structure of the dataset. We hope it will be helpful to you.
