### ISSUE TITLE
checkpoint downloading: This repository is over its data quota

### ISSUE THREAD

**Issue by 920394171** [WkEEn/PAMA#3]
The checkpoint pre-training file appears unable to download when I am pulling the github project code. More details are as below:

$ git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/WkEEn/PAMA.git/info/lfs'

Is there another channel or way to download this file? Or if it's easier send it straight to me at 2024141283@bupt.cn. Thank you for your excellent work!

**Comment by WkEEn** [comment]
Thanks for your reminder. We have uploaded the pre-training file in hugging face (https://huggingface.co/wkeen/pama/tree/main).
